modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="scalar_utils"
version="1.19.4-5.2.2"
displayName="Scalar Utils 5: Definitive Edition"
logoFile="scalarutils5.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Another Evolution For Scalar Utils.
'''

[[dependencies.scalar_utils]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.4-5.1.4.2,)"
    ordering="NONE"
    side="BOTH"