modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="scalar_utils"
version="1.20.1-5.4.7"
displayName="Scalar Utils 5: Definitive Edition"
logoFile="scalarutils5.png"
authors="Lemon_Juiced & Scalar Team"

description='''
Another Evolution For Scalar Utils.
'''

[[dependencies.scalar_utils]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="curios"
    mandatory=true
    versionRange="[5.2.0-beta.3+1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.20.1-1.0.17,)"
    ordering="NONE"
    side="BOTH"