modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="scalar_utils"
version="1.20-5.4.0"
displayName="Scalar Utils 5: Definitive Edition"
logoFile="scalarutils5.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Another Evolution For Scalar Utils.
'''

[[dependencies.scalar_utils]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="curios"
    mandatory=true
    versionRange="[5.2.0-beta.1+1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.20-1.0.10,)"
    ordering="NONE"
    side="BOTH"