modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"

[[mods]]
modId="scalar_utils"
version="1.19.3-5.1.0"
displayName="Scalar Utils 5: Definitive Edition"
logoFile="scalarutils5.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Another Evolution For Scalar Utils.
'''

[[dependencies.scalar_utils]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalar_utils]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.3-5.1.1.2,)"
    ordering="NONE"
    side="BOTH"